include fastcgi_params;
fastcgi_pass jiuin_php_primary;
fastcgi_param SCRIPT_FILENAME __JIUIN_PHP_PUBLIC_DIR__/index.php;
fastcgi_param SCRIPT_NAME /index.php;
fastcgi_param HTTP_HOST $host;
fastcgi_param HTTP_X_REAL_IP $http_x_real_ip;
fastcgi_param HTTP_X_FORWARDED_FOR $http_x_forwarded_for;
fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;
fastcgi_param HTTP_X_FORWARDED_HOST $http_x_forwarded_host;
fastcgi_param HTTPS on;
fastcgi_intercept_errors on;
fastcgi_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
fastcgi_next_upstream_tries 1;
fastcgi_next_upstream_timeout 8s;
fastcgi_connect_timeout 2s;
fastcgi_send_timeout 30s;
fastcgi_read_timeout 30s;
error_page 500 502 503 504 = @jiuin_go_read_failover;
add_header X-Jiuin-Backend php always;
